version: "3.9"

services:
  app:
    build:
      context: .
      #override DEV to true when using this compose file
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"