apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: backup-services
data:
  pgpass: MTkyLjE2OC4xLjE1MTo1NDMyOmJvdF9iYWNrdGVzdDpwb3N0Z3JlczpBc2tMT1JBdjIK
  AWS_ACCESS_KEY_ID: QUtJQTJYRU9UVU5HVzNIN1RPVTc=
  AWS_SECRET_ACCESS_KEY: VFFPS1hSaXhRZkhtTXpWUXlCZ1NRRHlnamZvdGkvbDR1TS9qbXdORw==

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: bot-backtest-postgresql-backup-cron-job
  namespace: backup-services
spec:
  schedule: "0 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeName: pc1
          containers:
          - name: postgresql-backup-job-pod
            image: psql-backup-image
            imagePullPolicy: IfNotPresent
            env:
              - name: DBHOST
                value: "192.168.1.151"
              - name: DBPORT
                value: "5432"
              - name: DBNAME  
                value: "bot_backtest"
              - name: DBUSER
                value: "postgres"
              - name: S3_BUCKET
                value: "s3://asklora-postgres-backup/bot-backtest/"
              - name: PGPASS
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: pgpass
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: AWS_SECRET_ACCESS_KEY                
              - name: AWS_DEFAULT_REGION
                value: "ap-east-1"
            args:
            - /bin/bash
            - -c
            - bash /home/root/postgres-backup.sh;
            # - while true; do foo; sleep 10; done
          restartPolicy: OnFailure
      backoffLimit: 3